### PR TITLE
render async

### PR DESCRIPTION
**Pull request by hooopo**

### CODE REVIEW

**Comment by hooopo** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fhackershare.dev%2Fbookmarks&hl=zh_CN&tab=desktop

## mobile

image


## web

image

**Comment by songhuangcn** [comment]
赞赞

**Comment by nikolalsvk** [comment]
Hey folks, I noticed you are using render_async. I am the owner and maintainer and I am just wondering if you are happy with it?

Feel free to contact me if you think something can be improved or fixed. Cheers!

**Comment by hooopo** [comment]
> Hey folks, I noticed you are using render_async. I am the owner and maintainer and I am just wondering if you are happy with it?
> 
> Feel free to contact me if you think something can be improved or fixed. Cheers!

Yes, awesome gem. It has been deployed in production environment for lots of days, works great!

https://hackershare.dev

At first, async_render did not execute when I view back from other page, however finally,  options `nonce: true` fixed this issue.

**Comment by nikolalsvk** [comment]
Awesome, I couldn't be happier to hear that. Keep on doing a great job and let me know if I can help somehow in the future.

**Pull request merged**
